name: "CI"
on:
  pull_request:
  push:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # checkout the repo
      - run: >
          curl https://github.com/toitlang/toit/releases/download/toit-linux.tar.gz | tar -xz -
      - run: ls -laR
      # - uses: actions/upload-artifact@v2 # upload test results
      #   if: success() || failure() # run this step even if previous step failed
      #   with:
      #     name: test-results
      #     path: jest-junit.xml
